openapi: 3.0.1
info:
  title: MilCare Foundation Onlus API
  description: >-
    This is an open API for Milcare Foundations Onlus website developed by
    Sophisticated Kids team
  contact:
    name: Sophisticated Kids
    url: >-
      https://github.com/alaamjadi/WebDev_Hypermedia-4-Applications-Web-and-Multimedia
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  version: 2.0.0-oas3
servers:
  - url: https://milcare-association-dynamic-website.onrender.com/api
tags:
  - name: Service
    description: Services of the association
  - name: Event
    description: Events of the association
  - name: Person
    description: Members of the association
paths:
  /Events:
    get:
      tags:
        - Event
      summary: List of all the events of the association
      operationId: eventsGET
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Unexpected error
          content: {}
      x-swagger-router-controller: Event
  /Events/Y/{Year}/M/{Month}:
    get:
      tags:
        - Event
      summary: List of events of a month in a specific year
      operationId: eventsYearMonthGET
      parameters:
        - name: Year
          in: path
          description: Number of the Year of the events for filtering
          required: true
          schema:
            type: integer
            format: int64
        - name: Month
          in: path
          description: Number of the month of the events for filtering
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: Invalid month
          content: {}
      x-swagger-router-controller: Event
  /Events/{CodeEvent}:
    get:
      tags:
        - Event
      summary: Find an event with the event code
      operationId: eventsCodeEventGET
      parameters:
        - name: CodeEvent
          in: path
          description: Code of the event that we want
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: Invalid id
          content: {}
      x-swagger-router-controller: Event
  /Events/{CodeEvent}/Services:
    get:
      tags:
        - Event
      summary: List of all services of an event
      operationId: eventsCodeEventServicesGET
      parameters:
        - name: CodeEvent
          in: path
          description: Code of an event that we want the related services
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid Code
          content: {}
      x-swagger-router-controller: Event
  /Events/{CodeEvent}/Person:
    get:
      tags:
        - Event
      summary: List of all persons of an event
      operationId: eventsCodeEventPersonGET
      parameters:
        - name: CodeEvent
          in: path
          description: Code of an event that we want the related persons
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid Code
          content: {}
      x-swagger-router-controller: Event
  /Person:
    get:
      tags:
        - Person
      summary: List of all the persons of the association
      operationId: personGET
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '400':
          description: Unexpected error
          content: {}
      x-swagger-router-controller: Person
  /Person/{CodePerson}:
    get:
      tags:
        - Person
      summary: Find a person with the person code
      operationId: personCodePersonGET
      parameters:
        - name: CodePerson
          in: path
          description: Code of a person that we want
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid CodePerson
          content: {}
      x-swagger-router-controller: Person
  /Person/{CodePerson}/Services:
    get:
      tags:
        - Person
      summary: List of all services of a person
      operationId: personCodePersonServicesGET
      parameters:
        - name: CodePerson
          in: path
          description: Code of a person that we want the related services
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid person code
          content: {}
      x-swagger-router-controller: Person
  /Person/{CodePerson}/Events:
    get:
      tags:
        - Person
      summary: List of all events of a person
      operationId: personCodePersonEventsGET
      parameters:
        - name: CodePerson
          in: path
          description: Code of a person that we want the related events
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid person code
          content: {}
      x-swagger-router-controller: Person
  /Services:
    get:
      tags:
        - Service
      summary: List of all the services of the association
      operationId: servicesGET
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '400':
          description: Unexpected error
          content: {}
      x-swagger-router-controller: Service
  /Services/{CodeService}:
    get:
      tags:
        - Service
      summary: Find a service with the service code
      operationId: servicesCodeServiceGET
      parameters:
        - name: CodeService
          in: path
          description: Code of a service that we want
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: operation was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid Name
          content: {}
      x-swagger-router-controller: Service
  /Services/{CodeService}/Events:
    get:
      tags:
        - Service
      summary: List of all events of a service
      operationId: servicesCodeServiceEventsGET
      parameters:
        - name: CodeService
          in: path
          description: Code of a service that we want the related events
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid Name
          content: {}
      x-swagger-router-controller: Service
  /Services/{CodeService}/Person:
    get:
      tags:
        - Service
      summary: List of all persons of a service
      operationId: servicesCodeServicePersonGET
      parameters:
        - name: CodeService
          in: path
          description: Code of a service that we want the related persons
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '400':
          description: Unexpected error
          content: {}
        '404':
          description: invalid Name
          content: {}
      x-swagger-router-controller: Service
components:
  schemas:
    Event:
      title: Event
      required:
        - CodeEvent
        - Date
        - Images
        - Location
        - LongDescription
        - Name
        - ShortDescription
      type: object
      properties:
        CodeEvent:
          type: integer
          format: int64
        Name:
          type: string
        Date:
          type: string
          format: date-time
        Location:
          type: string
        Images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        ShortDescription:
          type: string
        LongDescription:
          type: string
      description: An event presented by the association
      example:
        CodeEvent: 1
        Name: Presentation of service X
        Date: '2020-05-25T17:00:00.000Z'
        Location: Milan
        Images:
          - Image1
          - Image2
          - Image3
          - Image4
        ShortDescription: Short description of the event
        LongDescription: Long description of the event
      xml:
        name: Event
    Person:
      title: Person
      required:
        - CodePerson
        - Images
        - LongDescription
        - Name
        - Role
      type: object
      properties:
        CodePerson:
          type: integer
          format: int64
        Name:
          type: string
        Role:
          type: string
        Images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        LongDescription:
          type: string
      description: Person X
      example:
        CodePerson: FistName-LastName
        Name: FistName LastName
        Role: Volunteer
        Images:
          - Image1
        LongDescription: Biography
      xml:
        name: Person
    Service:
      title: Service
      required:
        - Images
        - LongDescription
        - Name
        - ShortDescription
      type: object
      properties:
        Name:
          type: integer
          format: int64
        Images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        ShortDescription:
          type: string
        LongDescription:
          type: string
      description: A service offered by the association
      example:
        Name: Hospice
        Images:
          - Image1
          - Image2
          - Image3
          - Image4
          - Image4
          - Image5
          - Image6
        ShortDescription: short description of the service
        LongDescription: Long description of the service
      xml:
        name: Service
    Image:
      title: Image
      required:
        - Image1
      type: object
      properties:
        Image1:
          type: string
      description: ImageName.Extention
      example:
        Image1: Picture1.jpg
      xml:
        name: Image